name: ci-mobile

on:
  push:
    branches: [yazilim, dev, main]
    paths:
      - "mobile/**"
      - ".github/workflows/ci-mobile.yml"

  pull_request:
    paths:
      - "mobile/**"
      - ".github/workflows/ci-mobile.yml"

concurrency:
  group: ci-mobile-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flutter:
    name: Flutter kalite kontrolleri
    runs-on: ubuntu-latest

    steps:
      - name: Repository'yi checkout et
        uses: actions/checkout@v4

      # 1. SDK'yı otomatik önbelleğe alan standart action
      - name: Flutter ortamını kur
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.0'
          cache: true 

      - name: Flutter sürümünü doğrula
        run: flutter --version

   
      - name: Pub cache
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-${{ runner.os }}-${{ hashFiles('mobile/pubspec.lock') }}
          restore-keys: pub-${{ runner.os }}-

      - name: Bağımlılıkları yükle
        working-directory: mobile
        run: flutter pub get

      #- name: Format kontrolü
        #working-directory: mobile
        #run: dart format --set-exit-if-changed lib test

      - name: Statik analiz
        working-directory: mobile
        run: flutter analyze

      - name: Testleri çalıştır
        working-directory: mobile
        run: flutter test
